
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_aml'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_aml'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  run_date: 2022-09-01  #for sake of testing only
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_aml:
    # Config indicated by + and applies to all files under models/example/
    silver:
      +materialized: table
      +database: AML
      +schema: SILVER
      +snowflake_warehouse: COMPUTE_WH
    gold:
      +materialized: table
      +database: AML
      +schema: GOLD
      +snowflake_warehouse: COMPUTE_WH
    marts:
      +materialized: view
      +database: AML
      +schema: MARTS
      +snowflake_warehouse: COMPUTE_WH
