name: github-workflow      #name of the workflow
on: workflow_dispatch     #trigger on which the workflow starts
jobs:
  first-job:     #first job to run (give it any name)
    runs-on: ubuntu-latest      #the environment which this workflow will run on (like we have here the tests and code are running locally on windows)
    steps:
      - name: print greeting    #first step to run in this job (give it any name) 
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Bye-Bye"