name: github-workflow-with-filter-&-conditions      #name of the workflow
on:
    pull_request:   #event
        types:      # specific types of an event (if supported)
            - opened
            - closed
    push:  # another event
        branches:  # targeting a specific branches that only this workflow will run on push
            - main 
        paths:
            - '*.py' # will only trigger this workflow if the changed files ends with .py extension and off course with push in branch main 
jobs:
  first-job:     #first job to run (give it any name)
    runs-on: ubuntu-latest      #the environment which this workflow will run on (like we have here the tests and code are running locally on windows)
    steps:
      - name: print greeting    #first step to run in this job (give it any name) 
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Bye-Bye"